Implement Liquid Payout
alfagen/payment_services pull request #10
Opened 2021-02-15 17:08 UTC by m1ndg8mer

2021-02-15 18:09 UTC, m1ndg8mer commented
@anaumov Review please.

2021-02-16 07:05 UTC, anaumov requested changes
В целом класс, но есть что поправить)

+ надо добавить миграцию для создания выплат в кассе (прям PR сделать в основном репозитории)

По-хорошему в кассе надо вывести информацию по выплате. Но это уже отдельная задача.

2021-02-16 07:05 UTC, anaumov commented on lib/payment_services/liquid/payout_adapter.rb
> +      payout.update!(status: withdrawal[:state]) if withdrawal
Переживаю, что статусы в апи поменяются, а мы об этом не узнаем. Предлагаю сделать какой-то мапинг статусов liquid на наш. Если появится новый статус, мы увидем nil в статусе и поймем, что где-то проблема.

2021-02-16 07:05 UTC, anaumov commented on lib/payment_services/liquid/payout_adapter.rb
> +      # there are 2 types of error responses
Начинай, пожалуйста, комментарий с NOTE, если это объяснение.

2021-02-16 07:05 UTC, anaumov commented on lib/payment_services/liquid/payout_adapter.rb
> +      payout.pay!(withdrawal_id: response[:id]) if response[:id]
А если response[:id] нет, тогда что? как мы узнаем, что оплата не прошла?

2021-02-16 07:05 UTC, anaumov commented on lib/payment_services/liquid/payout_client.rb
> +  class PayoutClient < PaymentServices::Liquid::Client
Нужен дополнительный PayoutClient? Может стоить эти два метода в обычный клиент перенести?

2021-02-17 23:04 UTC, m1ndg8mer commented on lib/payment_services/liquid/client.rb
> +    def request_for(path, method, body: nil)
Не особо она нужна тут, согласен.

2021-02-17 23:04 UTC, m1ndg8mer commented on lib/payment_services/liquid/payout.rb
> +      return false if status.nil?
Можем, удалил)

2021-02-17 23:08 UTC, m1ndg8mer commented on lib/payment_services/liquid/payout.rb
> +    STATUSES = {
В доке их очень много, не думаю что они нам все нужны.
Можем все оставить, ТК обяснений по статусам там нету(

2021-02-17 23:10 UTC, m1ndg8mer commented on lib/payment_services/liquid/payout_client.rb
> +  class PayoutClient < PaymentServices::Liquid::Client
Согласен, можем всё в одном клиенте сделать.

2021-02-17 23:24 UTC, m1ndg8mer commented
@anaumov Добавил миграцию: https://github.com/alfagen/kassa-admin/pull/700

2021-02-18 08:11 UTC, anaumov commented on lib/payment_services/liquid/payout.rb
> +    STATUSES = {
Может тогда просто убрать?

2021-02-18 08:11 UTC, anaumov commented on lib/payment_services/liquid/payout.rb
> +    STATUSES = {
и сделать одну константу вроде SUCCESS_PAYOUT_STATE = 'processed'

2021-02-18 18:45 UTC, m1ndg8mer commented on lib/payment_services/liquid/payout.rb
> +    STATUSES = {
Можем убрать, и записывать текущий. Добавил константу.

2021-05-26 17:46 UTC, merged