Add ETH/ETC coins
alfagen/payment_services pull request #14
Opened 2021-03-02 08:53 UTC by m1ndg8mer

2021-03-03 00:06 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/invoicer.rb
> -          address = invoice.address.split(':').last
Это уже не нужно, тут пофиксили: https://github.com/alfagen/payment_services/commit/5693217eaed29501849e29c07407b646b798affb

2021-03-03 00:07 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/invoicer.rb
> +          received_amount = transaction[:received] ? transaction[:received][invoice.address] : transaction[:amount]
Для ETH/ETC/OMNI - `transaction[:amount]`

2021-03-03 00:08 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      hash = response[:payload][:txid] || response[:payload][:hex]
Для ETH/ETC - `hex`

2021-03-05 17:18 UTC, m1ndg8mer commented
@anaumov Review please.

2021-03-12 08:01 UTC, anaumov requested changes

2021-03-12 08:01 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      hash = response[:payload][:txid] || response[:payload][:hex]
Добавь, пожалуйста, комментарий. Т.к. это не очевидно

2021-03-12 08:01 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      raise "Didn't get tx hash" unless hash
Не экономим буквы в ошибках) `Didn't get transaction hash`

2021-03-12 17:33 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/clients/ethereum_client.rb
> +        currency == 'eth' ? 'rinkeby' : 'mordor'
mordor - это аналог testnet для Ethereum Classic.
Убрал это, Рома попросил везде mainnet поставить.

2021-03-18 11:28 UTC, anaumov commented on lib/payment_services/crypto_apis/client.rb
> +  def class_name
class_name — очень абстрактно, сходу не ясно что такое. Давай как-то вроде coin_class_name

2021-03-18 11:28 UTC, anaumov commented on lib/payment_services/crypto_apis/client.rb
> +  BASE_CLIENT = 'BaseClient'
BASE_CLIENT_CLASS

2021-03-18 11:28 UTC, anaumov commented on lib/payment_services/crypto_apis/client.rb
> +  CLIENTS = {
CURRENCY_TO_CLIENTS

2021-03-18 11:28 UTC, anaumov commented on lib/payment_services/crypto_apis/clients/base_client.rb
> +      NETWORK = 'mainnet'
всегда?

2021-03-18 11:28 UTC, anaumov commented on lib/payment_services/crypto_apis/invoicer.rb
> +          received_amount = transaction[:received] ? transaction[:received][invoice.address] : transaction[:amount]
напиши, пожалуйста, в комментарии выше

2021-03-18 15:37 UTC, closed without merging