Payout adapters: refresh_status improvements
alfagen/payment_services pull request #15
Opened 2021-03-03 15:19 UTC by m1ndg8mer

2021-03-03 15:20 UTC, m1ndg8mer commented
@anaumov Review please.

2021-03-04 09:13 UTC, anaumov requested changes

2021-03-04 10:00 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout.rb
> -      txid
Да, для записи txid в коммент ордера. Теперь возвращаем в другом месте.

2021-03-04 10:12 UTC, m1ndg8mer commented on lib/payment_services/any_money/payout_adapter.rb
> +    def refresh_status!(payout_id)
Без этого не найдём нужный payout, когда будем из воркера вызывать.

2021-03-05 06:51 UTC, anaumov commented on lib/payment_services/any_money/payout.rb
>        status == 'done'
а если он зафейлился это же тоже `complete?`. Complete — это все, дальше он не изменится, это не success

2021-03-05 09:08 UTC, m1ndg8mer commented on lib/payment_services/any_money/payout.rb
>        status == 'done'
Добавил новый статус - failed чтобы это исправить.

2021-03-18 15:36 UTC, closed without merging