Crypto APIs - BitcoinCash
alfagen/payment_services pull request #2
Opened 2021-01-04 10:04 UTC by m1ndg8mer

# В этой задаче
Подключим криптошлюз Crypto APIs и реализуем прием / выплаты Litecoin через него.

## Вводные 
API key:
`d90c90997ea7f3d72f2fd15019f733638c7381ae`

Документация [по ссылке](https://docs.cryptoapis.io/rest-apis/blockchain-as-a-service-apis/btc/index#general-information).

## Чек-лист
- [ ] Прием
- [ ] Выплаты

## Логика
### Прием платежей
Для отслеживания платежей на прием будем использовать метод - [Get Basic Transactions By Address](https://docs.cryptoapis.io/rest-apis/blockchain-as-a-service-apis/bch/index#bch-address-transactions-endpoint).
Кошельки настроим так, чтобы одномоментно пользователям выводился один уникальный кошелек (Это уже сейчас можно настроить в платежке).
Кейс проверки тогда будет примерно такой:
1. Смотрим последний платеж по кошельку; _// Проверяем каждые 5 минут_
2. Сравниваем его по сумме с тем, что в заявке
3. Если совпадает - запоминаем его и ждем, пока в нем не будет 2 подтверждения
4. Когда транзакция получила 2 подтверждения - кидаем заявку в новые

### Выплаты с кошельков
Для совершения выплат с кошельков будем использовать метод - [Prepare, Sign and Broadcast a Transaction](https://docs.cryptoapis.io/rest-apis/blockchain-as-a-service-apis/bch/index#bch-transactions-new-transactions)
Кошельки добавим в ручную, Я их сам создам.
В кошельках необходимо будет добавить поля `wif` и `api key`, для взаимодействия с ними или использовать существующие поля (Api key / Api secret).
При совершении выплаты, должна быть возможность выплаты средств с нескольких кошельков.

Для отслеживания выплат с кошельков будем использовать метод [Get Transaction Details By Transaction ID (Txid)](https://docs.cryptoapis.io/rest-apis/blockchain-as-a-service-apis/bch/index#bch-transactions-transaction-txid-endpoint), используя Transaction ID (Txid), который мы получим после совершения выплаты.

2021-01-06 06:46 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      Payout.create!(amount_cents: amount_cents, order_public_id: order.public_id, destination_address: destination_address, fee: fee)
Не понятно как рассчитываеться `fee`. Если это константый % от `amount_cents` то можна отказаться от этой зависимости.

2021-01-06 10:57 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      payout = Payout.new(amount: amount, order_public_id: order.public_id, destination_address: destination_address, fee: fee)
Or we could use `recommended` fee from [Get Transactions Fee](https://docs.cryptoapis.io/rest-apis/blockchain-as-a-service-apis/bch/index#bch-hd-wallet-transactions-size) endpoint to refuse `fee` dependency.

2021-01-06 10:59 UTC, m1ndg8mer commented
@vsezbs Review please.

2021-01-06 20:28 UTC, anaumov requested changes
Так то клево, но вопросы есть)

2021-01-06 20:28 UTC, anaumov commented on lib/payment_services/crypto_apis/client.rb
> +        url: "#{API_URL}/bc/bch/#{NETWORK}/address/#{address}/basic/transactions",
как будем работать с биткойнами после такого обновления?

2021-01-06 20:28 UTC, anaumov commented on lib/payment_services/crypto_apis/client.rb
> +        url: "#{API_URL}/bc/bch/#{NETWORK}/txs/basic/txid/#{transaction_id}",
тут тоже

2021-01-06 20:28 UTC, anaumov commented on lib/payment_services/crypto_apis/payout.rb
> +    def complete_payment?
payout?

2021-01-06 20:28 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def create_payout(amount, destination_address, fee)
лучше использовать именнованные параметры, чтобы не перепутать порядок (amount:, address:, fee:)

2021-01-06 20:28 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      payout = Payout.new(amount: amount, order_public_id: order.public_id, destination_address: destination_address, fee: fee)
как рассчитать fee?

2021-01-06 20:28 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def initialize(order:, payout_wallets:)
сейчас при инициализации мы передаем в конструктор только кошелек для выплаты, без заявки

2021-01-06 20:28 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +        payout.payout_payments.new(wallet_id: wallet_id, amount: payout_amount)
так вроде с каждого кошелька снимется одинаковая сумма? как убедится, что сумма выплат не больше чем итоговая?

2021-01-06 20:28 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      payout.pay!(txid: response[:payload][:txid])
всегда возвращает транзакцию?

2021-01-06 20:28 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      payout.update!(confirmation: transaction[:confirmations])
confirmations?

2021-01-06 20:28 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      payout.payout_payments.inject([]) do |memo, payment|
почему не map? вроде проще читать будет

2021-01-06 20:28 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_payment.rb
> +    self.table_name = 'crypto_apis_payout_payments'
лучше просто payouts. Выплаты — это проще чем платежи по выплатам.

2021-01-06 20:28 UTC, anaumov commented on lib/payment_services/crypto_apis/wallet.rb
> +    self.table_name = 'crypto_apis_wallets'
зачем нам надо хранить балансы кошельков?

2021-01-08 15:51 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +        payout.payout_payments.new(wallet_id: wallet_id, amount: payout_amount)
Добавил проверки.
Нет, будет снято с разных кошелькев указанная сумма. Пример для btc: https://docs.cryptoapis.io/rest-apis/blockchain-as-a-service-apis/btc/index#btc-transactions-new-transactions

2021-01-08 15:57 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_payment.rb
> +    self.table_name = 'crypto_apis_payout_payments'
payouts уже занято :)
Можно было бы обойтись и без этой таблицы, но думаю полезно будет хранить информацию в базе о том какие кошельки и на какие суммы были задействованны для конкретного payout.
Можно просто сделать Payment модель и payments таблицу, но предположу что вы такую уже используете.

2021-01-08 15:57 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/wallet.rb
> +    self.table_name = 'crypto_apis_wallets'
Убрал.

2021-01-08 16:04 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def initialize(api_key:, currency:, payout_wallets:)
добавил api_key параметр, нам он нужен для запросов на cryptoapis. Также добавил currency параметр чтобы этот адаптер можно было использовать для любой валюты.
Протестировал для bch, для других нету api_key :( Но смею предположить что теперь invoicer и payout_adapter работают для всех валют что есть на cryptoapis!

2021-01-08 16:17 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def create_payout(amount:, address:, fee:)
Для рассчета fee можем использовать recommended поле из [Get Transactions Fee](https://docs.cryptoapis.io/rest-apis/blockchain-as-a-service-apis/bch/index#bch-transactions-fee-endpoint)
Но оно уже устарело, могут удалить в любой момент..

2021-01-08 16:18 UTC, m1ndg8mer commented
@anaumov One more check please.

2021-01-11 08:45 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def create_payout(amount:, address:, fee:)
Есть также вариант рассчитать самому размер будущей транзакции: [Transactions Fees](https://docs.cryptoapis.io/rest-apis/blockchain-as-a-service-apis/bch/index#transactions-fees) и умножить на `standard_fee_per_byte` из [Get Transactions Fee](https://docs.cryptoapis.io/rest-apis/blockchain-as-a-service-apis/bch/index#bch-transactions-fee-endpoint)

2021-01-11 14:09 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def create_payout(amount:, address:, fee:)
А зачем нам считать fee:? почему система не может их посчитать сама?

2021-01-12 12:41 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def create_payout(amount:, address:, fee:)
Как я понял транзакции идут по приоритету, ТЕ сперва пройдут транзакции с самым большим `fee`.
Отсюда и возможность указать это значения, это как указывать срочность той или инной транзакции.

2021-01-12 13:08 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def create_payout(amount:, address:, fee:)
А какие бывают строчности?

2021-01-12 13:45 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def create_payout(amount:, address:, fee:)
fast - очень быстро
standard - дешёво и быстро (среднее значение последних 70 блоков, рекомендуют эту использовать)
slow - очень дёшево но долго

2021-01-12 14:23 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def initialize(wallet:)
Если я правильно понял https://github.com/alfagen/payment_services/pull/2#discussion_r555075221, то один PayoutAdapter должен отвечать за один кошелек, из какого уже и будет производиться выплата.

2021-01-12 17:56 UTC, m1ndg8mer commented
Сделал сравнение url-ов ендпоинтов некотоых валют которые мы используем в Invoicer и PayoutAdapter-e - отличие только в currency symbol. Протестировал для Litecoin - всё работает!

`Get Basic Transactions By Address:`

`btc:` https://api.cryptoapis.io/v1/bc/btc/testnet/address/n1s4jV66dGSX6TDezLRWZgcEuH5Sy2Pujg/basic/transactions
`bch:` https://api.cryptoapis.io/v1/bc/bch/testnet/address/qrqxlge4wjv7kttm0u9srqjttprhylsz6g84fhjgzf/basic/transactions
`ltc:` https://api.cryptoapis.io/v1/bc/ltc/testnet/address/mvymY6wswVHDh9iW3bSg7zRgJgcvwPdV9F/basic/transactions

`Get Basic Transaction Details By Transaction ID (Txid):

`btc:` https://api.cryptoapis.io/v1/bc/btc/testnet/txs/basic/txid/87f765dcf8af14d481587e03cbb3758deb6b73c6fff346f0be783e3cba8b402a
`bch:` https://api.cryptoapis.io/v1/bc/bch/testnet/txs/basic/txid/066100ef7304e0467aeac07b8f8866ddb30e6a0b8c935bc79f0870a081a88977
`ltc:` https://api.cryptoapis.io/v1/bc/ltc/testnet/txs/basic/txid/8882b4420afae95a49f429950db73467d4f1fe99fcf97c689fd7818d6e0ae067

`Prepare, Sign and Broadcast a Transaction:`

`btc:` https://api.cryptoapis.io/v1/bc/btc/testnet/txs/new
`bch:` https://api.cryptoapis.io/v1/bc/bch/testnet/txs/new
`ltc:` https://api.cryptoapis.io/v1/bc/ltc/testnet/txs/new

`Get Transaction Details By Transaction ID (Txid):`

`btc:` https://api.cryptoapis.io/v1/bc/btc/testnet/txs/txid/5a4ebf66822b0b2d56bd9dc64ece0bc38ee7844a23ff1d7320a88c5fdb2ad3e2
`bch:` https://api.cryptoapis.io/v1/bc/bch/testnet/txs/txid/066100ef7304e0467aeac07b8f8866ddb30e6a0b8c935bc79f0870a081a88977
`ltc:` https://api.cryptoapis.io/v1/bc/ltc/testnet/txs/txid/924e34052a093da9c9bb74ff1802034be5c98df811333a5da31437116ab81b5e

2021-01-13 13:17 UTC, anaumov requested changes

2021-01-13 13:17 UTC, anaumov commented on lib/payment_services/crypto_apis/client.rb
> +        url: "#{API_URL}/bc/#{currency}/#{NETWORK}/txs/basic/txid/#{transaction_id}",
Можно это `"#{API_URL}/bc/#{currency}/#{NETWORK}"` вынести в отдельный метод вроде `base_url`

2021-01-13 13:17 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def initialize(api_key:, currency:, payout_wallets:)
не увидел изменений. Инициализация сейчас проходит так.
```
    order_payout
      .payment_system
      .payout_adapter!
      .new(wallet: order_payout.wallet)
```

2021-01-13 13:17 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def initialize(api_key:, currency:, payout_wallets:)
```
    order_payout
      .payment_system
      .payout_adapter!
```
эта часть как раз содержит инициализированный класс

2021-01-13 13:17 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def create_payout(amount:, address:, fee:)
Давай захардкодим standard. Т.е. будем расчитывать для каждой выплаты fee прямо здесь, чтобы не делать этого на уровне приложения.

2021-01-13 13:17 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      payout.pay!(txid: response[:payload][:txid])
Не может быть такого, что в [:response] не будет [:txid]

2021-01-13 13:17 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def initialize(api_key:, currency:, payout_wallets:)
Давай уберем несколько кошельков. Для кажой платежки они будут разными. Одна выплата — один кошелек. На кошельки мы разбиваем платеж на уровне приложения.

2021-01-13 13:17 UTC, anaumov commented on lib/payment_services/crypto_apis/wallet.rb
> +    self.table_name = 'crypto_apis_wallets'
А у меня осталось

2021-01-13 13:18 UTC, anaumov commented on lib/payment_services/crypto_apis/wallet.rb
> +    self.table_name = 'crypto_apis_wallets'
Всмысле я имел в виду, что кошельки не нужны. Адрес будет в payout'e и сумма тоже

2021-01-13 14:24 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/client.rb
> +        url: "#{API_URL}/bc/#{currency}/#{NETWORK}/txs/basic/txid/#{transaction_id}",
Done, thanks.

2021-01-13 14:25 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def create_payout(amount:, address:, fee:)
Done.

2021-01-13 15:24 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      payout.pay!(txid: response[:payload][:txid])
Добавил проверку.

2021-01-13 15:25 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/wallet.rb
> +    self.table_name = 'crypto_apis_wallets'
Удалил.

2021-01-13 15:27 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def initialize(api_key:, currency:, payout_wallets:)
Уже кошелёк один, и это единственный параметр при инициализации: `.new(wallet: order_payout.wallet)`

2021-01-15 13:16 UTC, anaumov commented on lib/payment_services/crypto_apis/client.rb
> +    NETWORK = 'testnet'
Пишу, чтобы не забыть перед мерждем заменить testnet на mainnet

2021-01-15 13:27 UTC, anaumov requested changes
Зарезолвь, пожалуйста, конфлиткты.

2021-01-15 13:27 UTC, anaumov commented on lib/payment_services/crypto_apis/client.rb
> +    attr_reader :currency
давай его в private, где api_key определен

2021-01-15 13:27 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    attr_accessor :payout_id
если не используется снаружи — в private

2021-01-15 13:27 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def make_payout!
смотри какя сигнатура у make_payout!
```
def make_payout!(amount:, payment_card_details:, transaction_id:, destination_account:)
```
Посмотри в классе base. Мы туда передаем сумму и адрес (amount и destination_account). Сделай, пожалауйста, также.

2021-01-15 13:27 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def refresh_status!
Это по аналогии с приемом, правильно?

2021-01-15 13:27 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +        PayoutClient.new(api_key: wallet.api_key, currency: wallet.currency.to_s.downcase)
обрати внимание, ключ может быть прописан у родительского кошелька. В invoicer пример.

2021-01-15 13:27 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def api_query
почему этим не занимается клиент?

2021-01-15 17:15 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def refresh_status!
Да.

2021-01-15 19:24 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/client.rb
> +    attr_reader :currency
Done.

2021-01-15 19:24 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    attr_accessor :payout_id
Done.

2021-01-15 19:25 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def make_payout!
Переделал.

2021-01-15 19:25 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +        PayoutClient.new(api_key: wallet.api_key, currency: wallet.currency.to_s.downcase)
Доделал.

2021-01-15 19:25 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def api_query
Уже занимается :)

2021-01-16 14:47 UTC, anaumov reviewed
Еще пара правок и можем пробовать затестить!

Напиши, пожалуйста, миграцию для создания payouts. Чтобы я создал таблицу в основном проекте. Можешь код прямо в комментарии написать.

2021-01-16 14:47 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      return if payout.pending?
paid?

2021-01-16 14:47 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      super
Если super, то можно его просто удалить)

2021-01-16 14:47 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def make_payout(amount:, payment_card_details:, transaction_id:, destination_account:)
payment_card_details вроде не используется, можно не определять.

2021-01-16 14:47 UTC, anaumov commented on lib/payment_services/crypto_apis/payout_client.rb
> +      }
класс!

2021-01-16 17:21 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      super
Оставил чтобы отсечь ненужные параметры.

2021-01-16 17:22 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +    def make_payout(amount:, payment_card_details:, transaction_id:, destination_account:)
Удалил, как и `transaction_id`

2021-01-16 17:29 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      return if payout.pending?
Здесь нужен таки `pending?`
По умолчанию статус `pending?`, ТЕ там ещё нету `payout.txid`, который появляется после `make_payout!`. 
Без него нету смысла в запуске этото метода, отсюда такая проверка.

2021-01-16 17:35 UTC, m1ndg8mer commented on lib/payment_services/crypto_apis/payout_adapter.rb
> +      return if payout.pending?
Сейчас у пейаута 3 статуса:
- pending - стоит по умолчанию, ожидает вывода (вызова `make_payout!`)
- paid - транзакция отправлена, но ещё не получила 2 подтверждений
- completed - вывод подтверждён

Хотя в теории можно и от completed отказаться, но я бы оставил для большей информативности.

2021-01-16 17:35 UTC, m1ndg8mer commented
> Еще пара правок и можем пробовать затестить!
> 
> Напиши, пожалуйста, миграцию для создания payouts. Чтобы я создал таблицу в основном проекте. Можешь код прямо в комментарии написать.

@anaumov https://gist.github.com/m1ndg8mer/0714668cb4e1b34769cbbc3076ef1466

2021-01-28 09:41 UTC, merged