Add Kuna payway
alfagen/payment_services pull request #25
Opened 2021-04-21 23:03 UTC by m1ndg8mer

2021-04-22 10:23 UTC, anaumov requested changes

2021-04-22 10:23 UTC, anaumov commented on lib/payment_services/kuna/client.rb
> +      )
можно ниже перенести
```
body: params.merge(gateway: GATEWAY)
```

2021-04-22 10:23 UTC, anaumov commented on lib/payment_services/kuna/client.rb
> +    def build_request(uri:, method:, body: nil)
пора это в какой-нибудь base_client для всех вынести

2021-04-22 10:23 UTC, anaumov commented on lib/payment_services/kuna/client.rb
> +      nonce = (Time.now.to_i * 1000).to_s
в константу

2021-04-22 10:23 UTC, anaumov commented on lib/payment_services/kuna/client.rb
> +    def http(uri)
и это в base_client

2021-04-22 10:23 UTC, anaumov commented on lib/payment_services/kuna/client.rb
> +    def signature(url, params, nonce)
лучше использовать именованные параметры

2021-04-22 10:23 UTC, anaumov commented on lib/payment_services/kuna/client.rb
> +    def safely_parse(response)
и это в base_client

2021-04-22 10:23 UTC, anaumov commented on lib/payment_services/kuna/invoicer.rb
> +        fields: { required_field_name => order.num_ps1 },
num_ps1 => income_account

https://github.com/alfagen/kassa-admin/blob/master/app/models/concerns/order_aliases.rb#L57

2021-04-22 10:23 UTC, anaumov commented on lib/payment_services/kuna/invoicer.rb
> +        callback_url: "#{routes_helper.public_public_callbacks_api_root_url}/v1/kuna/receive_payment"
Мы прямо в payment_system указываем callback_url
https://github.com/alfagen/payment_services/blob/master/lib/payment_services/any_money/invoicer.rb#L26

2021-04-22 10:23 UTC, anaumov commented on lib/payment_services/kuna/invoicer.rb
> +      invoice.update!(payment_invoice_id: response['payment_invoice_id'])
Объедени, строчки, пожалуйста

2021-04-22 10:23 UTC, anaumov commented on lib/payment_services/kuna/invoicer.rb
> +      invoice.update!(pay_url: response['flow_data']['action']) if invoice.amount.to_f >= 5000
5000 в константу.

Условие вынеси, пожалуйста в отдельный метод, тогда комментарий будет не нужен `invoice.amount.to_f >= 5000`

2021-04-22 10:23 UTC, anaumov commented on lib/payment_services/kuna/invoicer.rb
> +        'qiwi'   => "qiwi_#{invoice.amount.currency.to_s.downcase}_hpp"
invoice.amount.currency.to_s.downcase повторяется три раза, давай в отдельный метод

2021-04-22 10:23 UTC, anaumov commented on lib/payment_services/kuna/invoicer.rb
> +        )
Можно в одну строчку

2021-04-22 14:46 UTC, m1ndg8mer commented
@anaumov Предлагаю вынести фикс дублирования кода/добавления base_client-a в отдельную задачу.
Мы используем разные варианты этих методов, в задаче нужно будет придумать общий случай для всех + проверить что ничего не поломалось.

2021-04-22 14:46 UTC, m1ndg8mer commented on lib/payment_services/kuna/client.rb
> +    def build_request(uri:, method:, body: nil)
https://github.com/alfagen/payment_services/pull/25#issuecomment-824906754

2021-04-22 14:46 UTC, m1ndg8mer commented on lib/payment_services/kuna/client.rb
> +    def http(uri)
https://github.com/alfagen/payment_services/pull/25#issuecomment-824906754

2021-04-22 14:46 UTC, m1ndg8mer commented on lib/payment_services/kuna/client.rb
> +    def safely_parse(response)
https://github.com/alfagen/payment_services/pull/25#issuecomment-824906754

2021-04-22 16:30 UTC, m1ndg8mer commented on lib/payment_services/kuna/client.rb
> +      nonce = (Time.now.to_i * 1000).to_s
Сделал константой, но при запросе ошибка о невалидном nonce.
Видимо нужно таки вычислять при вызове..

2021-04-23 06:39 UTC, anaumov commented on lib/payment_services/kuna/client.rb
> +      nonce = (Time.now.to_i * 1000).to_s
тогда в метод
```
def time_now_milliseconds
  Time.now.strftime("%s%3N")
end
```

2021-04-23 06:43 UTC, anaumov commented on lib/payment_services/kuna/client.rb
> +      url.slice!(API_URL)
зачем делать slice, если можно просто использовать API_URL?

2021-04-23 06:43 UTC, anaumov commented on lib/payment_services/kuna/invoicer.rb
> +    FOR_DIRECT_PAY_AMOUNT = 5000
DIRECT_AMOUNT_THRESHOLD

2021-04-23 06:45 UTC, anaumov commented on lib/payment_services/kuna/invoicer.rb
> +      invoice.amount.to_f >= FOR_DIRECT_PAY_AMOUNT && payway == 'visamc'
Почему to_f? Лучше константу перевести в центы, чтобы не делать лишних преобразований DIRECT_AMOUNT_THRESHOLD_CENTS

2021-04-23 06:45 UTC, anaumov commented on lib/payment_services/kuna/invoicer.rb
> +      invoice = Invoice.find_by!(order_public_id: order.public_id)
ниже метод, который находит инвойс

2021-04-23 06:47 UTC, anaumov commented on lib/payment_services/kuna/payout_adapter.rb
> +      response = response.first if response.is_a? Array
Не понимаю. Если апи всегда отдает массив, тогда зачем проверка на `is_a? Array`

2021-04-23 10:54 UTC, m1ndg8mer commented on lib/payment_services/kuna/client.rb
> +      url.slice!(API_URL)
Тут нужна часть именно без API_URL. ТЕ:

`/v3/auth/merchant/deposit`
`/v3/auth/withdraw`
`/v3/auth/withdraw/details`

2021-04-23 11:12 UTC, m1ndg8mer commented on lib/payment_services/kuna/client.rb
> +      nonce = (Time.now.to_i * 1000).to_s
Вынес.
Для signature нужно такое же значения как хедере, передал параметром.

2021-04-23 11:20 UTC, m1ndg8mer commented on lib/payment_services/kuna/payout_adapter.rb
> +      response = response.first if response.is_a? Array
Всегда только для `client.create_payout`
Но если вернёт ошибку, то будет хеш. Добавил лишнюю строчку тут, чтобы не делать лишних проверок ниже:
`if response['messages']` вернет ошибку, если будет Array

2021-04-23 11:35 UTC, merged