Шлюз Obmenka: прием платежей
alfagen/payment_services pull request #38
Opened 2021-06-03 17:59 UTC by m1ndg8mer

2021-06-03 18:04 UTC, m1ndg8mer commented on lib/payment_services/obmenka/invoicer.rb
> +      available_options = {
Тут могут быть и другие опции в будущем, поэтому сделал таким обpазом. Кстати у них тоже RUR)

2021-06-03 18:06 UTC, m1ndg8mer commented on lib/payment_services/obmenka/client.rb
> +      Base64.encode64(sign_string)
И это не шутка))

base64_encode(md5($salt . base64_encode(sha1($data, true)) . $salt, true))

2021-06-04 05:31 UTC, anaumov requested changes

2021-06-04 05:31 UTC, anaumov commented on lib/payment_services/obmenka/client.rb
> +    def headers(params)
лучше прямо в хедер передавать подпись. В таком случае не надо разбираться зачем мы передаем body в headers, в виде переменной params, а в коде headers не надо понимать какие params передаются.

```ruby
headers(build_signarutre(body))
....
def headers(signature)
end

def build_signature(request_body)
end

```

2021-06-04 05:31 UTC, anaumov commented on lib/payment_services/obmenka/client.rb
> +      sign_string = Digest::MD5.digest(sign_string)
Жесть) чтобы никто не догадался!

2021-06-04 05:31 UTC, anaumov commented on lib/payment_services/obmenka/client.rb
> +      sign_string = Digest::MD5.digest(sign_string)
> secret_key + sign_string + secret_key

прикольно, длина ключа увеличивается в два раза без увеличения длины ключа)

2021-06-04 05:31 UTC, anaumov commented on lib/payment_services/obmenka/invoice.rb
> +      update!(provider_state: response['status'])
передавай сразу `provider_status`, зачем модели знать как устроен ответ от сервера.

2021-06-04 05:31 UTC, anaumov commented on lib/payment_services/obmenka/invoice.rb
> +    end
а зачем эти методы? ты же используешь методы с восклицательным знаком на конце

2021-06-04 05:31 UTC, anaumov commented on lib/payment_services/obmenka/invoicer.rb
> +
три пустые строки явно лишние)

2021-06-04 05:31 UTC, anaumov commented on lib/payment_services/obmenka/invoicer.rb
> +
https://www.yegor256.com/2014/11/03/empty-line-code-smell.html

2021-06-04 05:31 UTC, anaumov commented on lib/payment_services/obmenka/invoicer.rb
> +
и тут пустая

2021-06-04 05:31 UTC, anaumov commented on lib/payment_services/obmenka/invoicer.rb
> +
Можно вынести `build_invoice_params` в отдельный метод, будет чище

2021-06-04 05:31 UTC, anaumov commented on lib/payment_services/obmenka/invoicer.rb
> +
и тут пустая

2021-06-04 05:31 UTC, anaumov commented on lib/payment_services/obmenka/invoicer.rb
> +      available_options = {
давай их в константу вынесем

2021-06-04 05:31 UTC, anaumov commented on lib/payment_services/obmenka/invoicer.rb
> +
и тут пустая

2021-06-04 12:32 UTC, merged