Implement liquid invoicer
alfagen/payment_services pull request #4
Opened 2021-01-27 17:21 UTC by m1ndg8mer

2021-01-27 18:08 UTC, m1ndg8mer commented
Проверил подпись - запросы идут: ![](http://joxi.ru/5mdggLYu8Q8N4r.jpg)

2021-01-27 18:11 UTC, m1ndg8mer commented on lib/payment_services/liquid/invoicer.rb
> +        Client.new(api_token_id: wallet.merchant_id, api_secret: api_key, currency: wallet.currency.to_s)
Для запросов на Liquid API кроме `api_key` есть ещё `api_token_id`. Пока что использовал `wallet.merchant_id`, но
@anaumov может есть другое в таблице `wallets`? или можем добавить.

2021-01-27 18:15 UTC, m1ndg8mer commented on lib/payment_services/liquid/invoicer.rb
> +      invoice.pay!(payload: transaction)
Если транзакция появилась в кошельке - она уже подтверждена.
Liquid делает эту проверку на своей стороне и возвращает нам только подтвержденные.

2021-01-27 18:18 UTC, m1ndg8mer commented
@anaumov Review please.

2021-02-03 15:00 UTC, anaumov commented on lib/payment_services/liquid/invoicer.rb
> +      invoice.pay!(payload: transaction)
ок!

2021-05-21 08:46 UTC, anaumov requested changes

2021-05-21 08:46 UTC, anaumov commented on lib/payment_services/liquid/client.rb
> +      request_for("/transactions?transaction_type=funding&currency=#{currency}")
если параметры передавать хешом, будет читабельнее)

2021-05-21 08:46 UTC, anaumov commented on lib/payment_services/liquid/client.rb
> +      @api_wallet = Wallet.find_by(name_group: WALLET_NAME_GROUP)
Это мы прямо в кассе ищем?

2021-05-21 08:46 UTC, anaumov commented on lib/payment_services/liquid/client.rb
> +      @api_wallet = Wallet.find_by(name_group: WALLET_NAME_GROUP)
||=

2021-05-21 08:46 UTC, anaumov commented on lib/payment_services/liquid/invoice.rb
> +      Order.find_by(public_id: order_public_id) || PreliminaryOrder.find_by(public_id: order_public_id)
@order ||=

2021-05-21 08:46 UTC, anaumov commented on lib/payment_services/liquid/invoicer.rb
> +      update_invoice_details(invoice: invoice, transaction: transaction)
зачем передавить invoice, если он определен ниже?)

2021-05-21 08:46 UTC, anaumov commented on lib/payment_services/liquid/invoicer.rb
> +    def invoice
может в private?

2021-05-21 08:46 UTC, anaumov commented on lib/payment_services/liquid/invoicer.rb
> +    def async_invoice_state_updater?
_updater => _update

2021-05-21 08:46 UTC, anaumov commented on lib/payment_services/liquid/invoicer.rb
> +      raise response['message'] if response['message']
мы где ловим это исключение?

2021-05-21 08:46 UTC, anaumov commented on lib/payment_services/liquid/invoicer.rb
> +      end if response['models']
лучше выше сделать `return unless response['models']`, читать будет проще

2021-05-21 16:08 UTC, m1ndg8mer commented on lib/payment_services/liquid/invoicer.rb
> +    def async_invoice_state_updater?
Тут таки `updater`.
https://github.com/alfagen/kassa-admin/blob/master/app/models/preliminary_order.rb#L277

2021-05-21 16:09 UTC, m1ndg8mer commented on lib/payment_services/liquid/invoicer.rb
> +      raise response['message'] if response['message']
Через `InvoicePaymentConfirmationWorker` идёт на bugsnap

2021-05-21 16:31 UTC, m1ndg8mer commented on lib/payment_services/liquid/client.rb
> +      @api_wallet = Wallet.find_by(name_group: WALLET_NAME_GROUP)
Да, сделаем кошелек суто под хpанения API ключей для запросов (получения других кошелькев для оплаты)

2021-05-21 17:31 UTC, anaumov commented on lib/payment_services/liquid/invoicer.rb
> +        Client.new(api_token_id: wallet.merchant_id, api_secret: api_key, currency: wallet.currency.to_s)
api_secret

2021-05-21 17:32 UTC, anaumov commented on lib/payment_services/liquid/client.rb
> +      @api_wallet = Wallet.find_by(name_group: WALLET_NAME_GROUP)
так может быть много кошельков с одной name_group, нам пофиг какой?

2021-05-21 17:33 UTC, anaumov commented on lib/payment_services/liquid/invoicer.rb
> +      raise response['message'] if response['message']
давай сделаем тут класс ошибки и будем стрелять именнованную ошибку, проще будет разобраться

2021-05-23 14:52 UTC, m1ndg8mer commented on lib/payment_services/liquid/client.rb
> +      @api_wallet = Wallet.find_by(name_group: WALLET_NAME_GROUP)
Да, Рома уже в курсе что для Liquid нужно ставить `LIQUID_API_KEYS`.

2021-05-24 11:44 UTC, anaumov commented on lib/payment_services/liquid/client.rb
> +      @api_wallet ||= Wallet.find_by(name_group: WALLET_NAME_GROUP)
Все таки это мне не нравится. Клиент отвечает за взаимодействие с сервисом и ничего не должен знать о устройстве моделей. Сделай, пожалуйста, чтобы все секреты передавались во время инициализации клиента. 

Например
https://github.com/alfagen/payment_services/blob/master/lib/payment_services/ali_kassa/client.rb#L13
https://github.com/alfagen/payment_services/blob/master/lib/payment_services/any_money/client.rb#L10

2021-05-24 14:36 UTC, m1ndg8mer commented on lib/payment_services/liquid/client.rb
> +      @api_wallet ||= Wallet.find_by(name_group: WALLET_NAME_GROUP)
@anaumov Done.

2021-05-24 14:36 UTC, merged