Exmo: выплаты
alfagen/payment_services pull request #54
Opened 2021-08-10 16:32 UTC by m1ndg8mer

Related to

2021-08-11 09:55 UTC, anaumov requested changes
давай доп реквестом все в base класс, потом этот вольём

2021-08-11 09:55 UTC, anaumov commented on lib/payment_services/exmo/client.rb
> +        url: "#{API_URL} + /withdraw_crypt",
"#{API_URL}/withdraw_crypt"

2021-08-11 09:55 UTC, anaumov commented on lib/payment_services/exmo/client.rb
> +        )
в одну строчку

2021-08-11 09:55 UTC, anaumov commented on lib/payment_services/exmo/client.rb
> +    end
ну давай уже в base вынесем, сколько можно тянуть)

2021-08-11 09:55 UTC, anaumov commented on lib/payment_services/exmo/client.rb
> +    end
и это

2021-08-11 09:55 UTC, anaumov commented on lib/payment_services/exmo/client.rb
> +    end
и это

2021-08-11 09:55 UTC, anaumov commented on lib/payment_services/exmo/payout_adapter.rb
> +      payout = Payout.find(payout_id)
а если не найдет?

2021-08-13 13:45 UTC, m1ndg8mer commented on lib/payment_services/exmo/payout_adapter.rb
> +      payout = Payout.find(payout_id)
ActiveRecord::RecordNotFound, и мы сможем это увидеть на багснепе и обработать

2021-08-16 13:10 UTC, anaumov commented on lib/payment_services/exmo/invoicer.rb
> +        transaction['amount'] == invoice.amount.to_d && time_diff.round.minutes < TRANSACTION_TIME_THRESHOLD
сложно, давай разобьем, чтобы проще было читать.
```ruby
transactions.find { |transaction| matches_amount_and_timing?(transaction) }
...
def matches_amount_and_timing?(transaction)
  transaction['amount'] == invoice.amount.to_d && match_time_invertal?(transaction)
end

def match_time_interval?(transaction)
     transaction_created_at_utc = DateTime.strptime(transaction[:created].to_s,'%s').utc
     invoice_created_at_utc = invoice.created_at.utc

     invoice_created_at_utc < transaction_created_at_utc && created_in_valid_interval?(transaction_created_at_utc, invoice_created_at_utc)
end

def created_in_valid_interval?(transaction_time, invoice_time)
     interval = (transaction_time - invoice_time
     interval_in_minutes = (interval / 1.minute).round.minutes
     interval_in_minutes < TRANSACTION_TIME_THRESHOLD
end
```

2021-08-17 14:56 UTC, merged